### ISSUE TITLE
🐛 Format on save lint fixes garble the file

### ISSUE THREAD

**Issue by valeneiko** [biomejs/biome-vscode#241] opened 2024-06-15 19:27 UTC
### VS Code version

1.90.1

### Extension version

2.3.0

### Biome version

1.8.1

### Operating system

- [X] Windows
- [ ] macOS
- [X] Linux

### Description

Format on save produces wrong output when multiple fixes for the same lint rule are applied to the same expression.

### Steps to reproduce

1. A `biome.json` config with linter enabled:
   ```jsonc
   // biome.json
   {
     "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
     "files": {
       "include": ["*.ts", "*.json"]
     },
     "formatter": {
       "enabled": false
     },
     "linter": {
       "enabled": true
     },
     "organizeImports": {
       "enabled": false
     }
   }
   ```
1. Create a TS file where `lint/complexity/useFlatMap` fails multiple times on the same expression:
   ```ts
   // index.ts
   Object.values(rules.lints.languages)
     .map((l) => Object.values(l))
     .flat()
     .map((l) => Object.values(l))
     .flat();
   ```
1. Configure VSCode to format on save:
   ```jsonc
   // .vscode/settings.json
   {
     "editor.formatOnSave": true,
     "editor.codeActionsOnSave": {
       "quickfix.biome": "explicit"
     },
     "[typescript]": {
       "editor.defaultFormatter": "biomejs.biome"
     }
   }
   ```
1. Save the file and observe the wrong output:
   ```ts
   // index.ts
   Object.values(rules.lints.languages)
     .flatMap((l) => Object.values(l))
     .map((l) => Object.values(l))
     .flatMapt();
   ```

### Expected behavior

Lint rule fixes to be correctly applied on save:
```ts
// index.ts
Object.values(rules.lints.languages)
  .flatMap((l) => Object.values(l))
  .flatMap((l) => Object.values(l));
```

### Does this issue occur when using the CLI directly?

No

**Comment by Sec-ant** [comment] 2024-06-16 02:05
I believe this is a duplicate of https://github.com/biomejs/biome/issues/2268 and https://github.com/biomejs/biome/issues/1570. Thanks for providing the example code.

**Closed by Sec-ant** 2024-06-16 02:05 UTC
Labels: Triage
