### ISSUE TITLE
🐛 Quickfix slows down saving files in VSCode 

### ISSUE THREAD

**Issue by jansedlon** [biomejs/biome-vscode#229] opened 2024-05-29 06:37 UTC
### VS Code version

1.90.0-insiders

### Extension version

2.2.3

### Biome version

1.7.3

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

When this config is enabled in vscode settings
```json
    "quickfix.biome": "explicit"
```

it slows down saving files in vscode. But not always 😅. When i type something and immediately hit `Cmd + Save`, there's like a second delay before the file is saved.

Interestingly enough, if i type something and **wait a second** and hit save, the file is saved immediately.

### Steps to reproduce

1. Enable `"quickfix.biome": "explicit"`,
2. Hit Cmd + Save immediately after typing something

### Expected behavior

It should save immediately

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs

Logs contain actions that happened when i entered "Enter" and immediately save

```plain text
[Trace - 8:36:03 AM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///Users/jansedlon/Work/Flixy/flixy/packages/prisma/index.ts",
        "version": 174
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 22,
                    "character": 20
                },
                "end": {
                    "line": 22,
                    "character": 20
                }
            },
            "rangeLength": 0,
            "text": "\n  "
        }
    ]
}


[Trace - 8:36:03 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/jansedlon/Work/Flixy/flixy/packages/prisma/index.ts",
    "diagnostics": [],
    "version": 174
}


[Trace - 8:36:03 AM] Sending request 'textDocument/codeAction - (409)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/jansedlon/Work/Flixy/flixy/packages/prisma/index.ts"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 95,
            "character": 0
        }
    },
    "context": {
        "diagnostics": [],
        "only": [
            "source.fixAll"
        ],
        "triggerKind": 2
    }
}


[Trace - 8:36:03 AM] Received response 'textDocument/codeAction - (409)' in 1ms.
Result: []


[Trace - 8:36:03 AM] Sending request 'textDocument/codeAction - (410)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/jansedlon/Work/Flixy/flixy/packages/prisma/index.ts"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 95,
            "character": 0
        }
    },
    "context": {
        "diagnostics": [],
        "only": [
            "source.organizeImports"
        ],
        "triggerKind": 2
    }
}


[Trace - 8:36:03 AM] Received response 'textDocument/codeAction - (410)' in 0ms.
Result: []


[Trace - 8:36:03 AM] Sending request 'textDocument/codeAction - (411)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/jansedlon/Work/Flixy/flixy/packages/prisma/index.ts"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 95,
            "character": 0
        }
    },
    "context": {
        "diagnostics": [],
        "only": [
            "quickfix.biome"
        ],
        "triggerKind": 2
    }
}


[Trace - 8:36:03 AM] Received response 'textDocument/codeAction - (411)' in 0ms.
Result: []


[Trace - 8:36:03 AM] Sending request 'textDocument/codeAction - (412)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/jansedlon/Work/Flixy/flixy/packages/prisma/index.ts"
    },
    "range": {
        "start": {
            "line": 23,
            "character": 2
        },
        "end": {
            "line": 23,
            "character": 2
        }
    },
    "context": {
        "diagnostics": [],
        "triggerKind": 2
    }
}


[Trace - 8:36:03 AM] Received response 'textDocument/codeAction - (412)' in 1ms.
Result: []


[Trace - 8:36:04 AM] Sending request 'textDocument/formatting - (413)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/jansedlon/Work/Flixy/flixy/packages/prisma/index.ts"
    },
    "options": {
        "tabSize": 2,
        "insertSpaces": true
    }
}


[Trace - 8:36:04 AM] Received response 'textDocument/formatting - (413)' in 2ms.
Result: [
    {
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 96,
                "character": 0
            }
        },
        "newText": "import { remember } from \"@epic-web/remember\";\nimport { handlePrismaLogging, logger } from \"@flixydev/logger\";\nimport { Prisma, PrismaClient, type Subscription } from \"@prisma/client\";\nimport { type Result, ResultAsync, errAsync } from \"neverthrow\";\n\nexport const prisma = remember(\"prisma\", () => {\n  const client = new PrismaClient({\n    log: [\n      {\n        level: \"query\",\n        emit: \"event\",\n      },\n    ],\n  });\n\n  handlePrismaLogging({\n    db: client,\n    logger: logger,\n    logLevels: [\"query\"],\n    slowQueryThresholdMs: 20,\n  });\n\n  client.$connect();\n\n  return client.$extends({\n    result: {\n      user: {\n        stripeActivated: {\n          needs: {\n            stripeConnectAccountId: true,\n            stripeDetailsSubmitted: true,\n          },\n          compute(data) {\n            return (\n              !!data.stripeConnectAccountId && !!data.stripeDetailsSubmitted\n            );\n          },\n        },\n      },\n    },\n    model: {\n      $allModels: {\n        async exists<T>(\n          this: T,\n          where: Prisma.Args<T, \"findFirst\">[\"where\"],\n        ): Promise<boolean> {\n          const context = Prisma.getExtensionContext(this);\n          // biome-ignore lint/suspicious/noExplicitAny: <explanation>\n          const result = await (context as any).findFirst({ where });\n\n          return result !== null;\n        },\n      },\n      user: {\n        async findActiveSubscription(userId: string) {\n          return prisma.subscription.findFirst({\n            where: {\n              userId,\n              status: {\n                in: [\"active\", \"trialing\"],\n              },\n              deletedAt: null,\n            },\n          });\n        },\n        async cancelActiveSubscription(\n          userId: string,\n        ): Promise<Result<Subscription, Error>> {\n          const activeSubscription = await this.findActiveSubscription(userId);\n\n          if (!activeSubscription) {\n            return errAsync(new Error(\"No active subscription found\"));\n          }\n\n          const update = await ResultAsync.fromPromise(\n            prisma.subscription.update({\n              where: {\n                id: activeSubscription.id,\n              },\n              data: {\n                cancelledAt: new Date(),\n              },\n            }),\n            (e) => e as Error,\n          );\n\n          return update;\n        },\n      },\n    },\n  });\n});\n\nexport * from \"@prisma/client\";\n"
    }
]


[Trace - 8:36:04 AM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///Users/jansedlon/Work/Flixy/flixy/packages/prisma/index.ts",
        "version": 175
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 23,
                    "character": 0
                },
                "end": {
                    "line": 24,
                    "character": 0
                }
            },
            "rangeLength": 3,
            "text": ""
        }
    ]
}


[Trace - 8:36:04 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/jansedlon/Work/Flixy/flixy/packages/prisma/index.ts",
    "diagnostics": [],
    "version": 175
}


[Trace - 8:36:04 AM] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "file:///Users/jansedlon/Work/Flixy/flixy/packages/prisma/index.ts"
    }
}


[Trace - 8:36:04 AM] Sending request 'textDocument/codeAction - (414)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/jansedlon/Work/Flixy/flixy/packages/prisma/index.ts"
    },
    "range": {
        "start": {
            "line": 23,
            "character": 0
        },
        "end": {
            "line": 23,
            "character": 0
        }
    },
    "context": {
        "diagnostics": [],
        "triggerKind": 2
    }
}


[Trace - 8:36:04 AM] Received response 'textDocument/codeAction - (414)' in 1ms.
Result: []
```

**Comment by nhedger** [comment] 2024-05-29 07:28
Do you have other extensions that run actions on save ?

**Comment by jansedlon** [comment] 2024-05-29 08:12
I disabled everything except biome and it was still happening.

PS: hmmm.. Interesting, when everything is disabled, it's still happening, sorry! How's that possible? That configuration should be biome specific?

**Comment by nhedger** [comment] 2024-05-29 09:09
What I meant is when you save a file, VS Code will run all "on save" actions, and sometimes other extensions register their own actions which can have an impact.

I see you mentioned using the insiders version of VS Code. Does that also happen in the stable version ?

**Comment by colinhacks** [comment] 2024-05-31 20:16
There appears to be a decent repro in this issue: https://github.com/biomejs/biome-vscode/issues/214

Link: https://github.com/OliverJAsh/biome-vscode-quickfix-import-issue/compare/1.7.3

I've also experienced this in Zod. You can pull down this branch to repro: https://github.com/colinhacks/zod/tree/slow-quickfix

```
$ gh repo clone colinhacks/zod
$ cd zod
$ git checkout slow-quickfix
$ yarn 
$ code .
```

I've introduced a formatting issue at the top of `src/index.ts`. Saving that file in VS Code should trigger the slow quickfixing. Interestingly I get faster fix-on-save with `"source.fixAll": "always"`. Does that behave in a meaningfully different way than `"quickfix.biome": "always"`?

**Comment by ragrag** [comment] 2024-09-10 10:23
@nhedger i am experiencing the same issue in .vue files, quick save is very slow (3 second delay) when i have those settings

```json
  "editor.codeActionsOnSave": {
    "quickfix.biome": "explicit"
  },
```

in extension host output i also see those messages

<img width="1003" alt="image" src="https://github.com/user-attachments/assets/aadef111-ca42-4b9d-8818-211a74980183">

**Comment by nhedger** [comment] 2024-09-10 10:26
Interesting, I'll definitely have a look, thanks for the details.

**Comment by emilte** [comment] 2024-09-12 12:54
I believe I'm experiencing the same thing. Something feels slow, but I have to mention that biome is very new for me still

**Comment by leotroche** [comment] 2024-09-16 12:24
I'm experiencing the same thing in:

| Software         | Versión |
| ---------------- | ------- |
| VS Code          | 1.93.1  |
| Extension        | 2.3.0   |
| Biome            | 1.9.1   |
| Operating System | Windows |

I set this setting in my vscode and apparently it works perfect, no lag:

```jsonc
"editor.codeActionsOnSave": {
  // "quickfix.biome": "explicit",
  "source.fixAll.biome": "explicit",
  "source.organizeImports.biome": "explicit"
},
```

Another thing I noticed is that the `"quickfix.biome": "explicit"` lag only affects `JS, JSX, TS, TSX` files.
No lag in CSS files.

**Comment by emilte** [comment] 2024-09-16 19:19
I'm not sure I have understood the difference between these settings, and I can't find clarity in the docs.
May I ask if anyone knows? I have posted a question here https://github.com/biomejs/biome-vscode/discussions/342

**Comment by ragrag** [comment] 2024-09-16 20:46
> I'm experiencing the same thing in:
> 
> Software	Versión
> VS Code	1.93.1
> Extension	2.3.0
> Biome	1.9.1
> Operating System	Windows
> I set this setting in my vscode and apparently it works perfect, no lag:
> 
> ```js
> "editor.codeActionsOnSave": {
>   // "quickfix.biome": "explicit",
>   "source.fixAll.biome": "explicit",
>   "source.organizeImports.biome": "explicit"
> },
> ```
> 
> Another thing I noticed is that the `"quickfix.biome": "explicit"` lag only affects `JS, JSX, TS, TSX` files. No lag in CSS files.

doesn't seem to work (atleast not in vue projects w/vue extension) with same warning in my previous comment

**Comment by nhedger** [comment] 2024-09-16 22:18
I wasn't able to reproduce using the previously provided reproductions. For those experiencing the same issue right now, please provide a minimal reproduction that triggers it.

**Comment by leotroche** [comment] 2024-09-17 10:36
1. In the cloned repository you will find the `index.js` file:

![{EB54CAA9-BECF-4C77-AB63-6FB31EBE66DF}](https://github.com/user-attachments/assets/b0073abe-5820-42f9-8a16-594404c0e492)

2. How to activate the bug?
If you press `Enter` to make line breaks and quickly press `Control + S` to save, you will see a delay between the time you save the file and the time the fix is ​​executed

![{A159C850-B34B-4094-AE97-2BDCA59EDBF2}](https://github.com/user-attachments/assets/3d2631dd-538f-483e-9f2f-4eec6d196a60)

After saving

![{EB54CAA9-BECF-4C77-AB63-6FB31EBE66DF}](https://github.com/user-attachments/assets/b0073abe-5820-42f9-8a16-594404c0e492)

The bug is present regardless of the `biome.json` configuration.

Important: 
You have to be fast, if you do the line break and wait more than a second before tapping `Control + S`, you will not see the delay.
I recommend to try it several times.

**Comment by mizdra** [comment] 2024-09-17 15:31
I have investigated this problem. I hope it is useful.

## Reproduction Test: Part 1

Apparently, the problem reproduces without any 3rd-party extensions. Surprisingly, it reproduces without vscode-biome.

The workspace used for reproduction is as follows:

`.vscode/settings.json`:
```json
{
    "editor.codeActionsOnSave": {
        "quickfix.biome": "explicit"
      }
}
```

`index.ts`:
```ts
function fn(){
    console.log('hello');
}
```

https://github.com/user-attachments/assets/56415cd5-d02e-4fd8-acc2-a5dcffb04932

This suggests that the problem is caused by something other than the vscode-biome.

## Reproduction Test: Part 2

The problem does not seem to reproduce with `.css`.

The workspace used for reproduction is as follows:

`.vscode/settings.json`:
```json
{
    "editor.codeActionsOnSave": {
        "quickfix.biome": "explicit"
      }
}
```

`index.css`:
```css
.foo {
    background: black;
}
```

https://github.com/user-attachments/assets/6719fd2a-a1d5-4591-ae13-10834259eca3

This suggests that the problem is `.ts` specific.

## Reproduction Test: Part 3

If you disable VS Code's built-in js/ts extension, the problem does not reproduce.

How to disable VS Code's built-in js/ts extension:

1. Select `Side Bar > ... > Show Running Extensions`
    - <img width="590" alt="image" src="https://github.com/user-attachments/assets/8e0197d8-acd9-4aab-a61e-ff60ae56536a">
2. Right-click `TypeScript and JavaScript Language Features` and select `Disable`
    - <img width="808" alt="image" src="https://github.com/user-attachments/assets/fce68253-f637-4808-99eb-66001fe31d24">
3. Restart VS Code

https://github.com/user-attachments/assets/a8ebed83-dc5e-4ade-9292-bcda18af25d9

---

From these tests, I believe the problem is caused by VS Code, VS Code's built-in js/ts extension (`TypeScript and JavaScript Language Features`), or tsserver.

I don't think vscode-biome has anything to do with this problem.

**Comment by mizdra** [comment] 2024-09-22 07:36
I have investigated this issue further. It appears to be a compatibility issue between `typescript-language-features` and the Biome extension.

However, I think I need to know about the `editor.codeActionsOnSave` spec to determine a solution to this problem. Therefore, I have written a question to the VS Code team. You can find it at

- https://github.com/microsoft/vscode-discussions/discussions/1664

**Comment by nhedger** [comment] 2024-09-22 08:15
Really appreciate the investigation @mizdra, I'll be following along!

**Comment by ragrag** [comment] 2024-09-22 13:01
it's worth noting that this issue also happens not only with ```typescript-language-features``` but also others like vue and ```Vue.volar``` extension in similar fashion.
(issue i already created on official vue tooling repo https://github.com/vuejs/language-tools/issues/4833)

**Comment by mizdra** [comment] 2024-09-22 13:43
@ragrag You are misunderstanding the problem. This problem is specific to `typescript-language-features`. The problem occurs because you have enabled both `Vue.volar` and `typescript-language-features`. If you enable `Vue.volar` and disable `typescript-language-features`, this problem should not occur.

`typescript-language-features` is not a 3rd-party extension, but a built-in extension of VS Code. To disable `typescript-language-features`, you need to perform a special operation. For details, please see https://github.com/biomejs/biome-vscode/issues/229#issuecomment-2356257770.

BTW: `Vue.volar` depends on `typescript-language-features`, so it won't work without it. `Vue.volar` uses [`contributes.typescriptServerPlugins`](https://code.visualstudio.com/api/references/contribution-points#contributes.typescriptServerPlugins) to attach the [TypeScript Language Service Plugin](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin) to the [tsserver](https://github.com/microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29) that is started by `typescript-language-features` [^1]. This allows tsserver to handle `*.vue`.

[^1]: https://github.com/vuejs/language-tools/blob/5a026761d246c77dd789b32200bf779a526a617d/extensions/vscode/package.json#L89

**Comment by ragrag** [comment] 2024-09-22 13:58
@mizdra what i'm trying to say is that i can confirm that the problem is still reproducible in my case when enabling ```Vue.volar``` and disabling ```typescript-language-features```

**Comment by mizdra** [comment] 2024-09-22 14:13
@ragrag Really? I couldn't reproduce it.

https://github.com/user-attachments/assets/4edd99ea-d366-4929-b960-20f9fc458473

Have you forgotten to restart VS Code? Even if you press the button to disable the extension, the extension will continue to operate until you restart VS Code. To completely disable the extension, you must restart VS Code.

**Comment by ragrag** [comment] 2024-09-22 14:20
> @ragrag Really? I couldn't reproduce it.
> 
> 
> 
> https://github.com/user-attachments/assets/4edd99ea-d366-4929-b960-20f9fc458473
> 
> 
> 
> Have you forgotten to restart VS Code? Even if you press the button to disable the extension, the extension will continue to activate until you restart VS Code. To completely disable the extension, you must restart VS Code.

Yeah i did.

I can reproduce this consistently on multiple medium-sized vue apps residing in a medium sized monorepo.

I can't seem to reproduce it on fresh vue apps so it's hard for me to isolate it and create a minimal repro but i will try when i have some time later

**Comment by mizdra** [comment] 2024-09-22 14:26
@ragrag 
> I can reproduce this consistently on multiple medium-sized vue apps residing in a medium sized monorepo.

Hmm. That's strange.

> I can't seem to reproduce it on fresh vue apps so it's hard for me to isolate it and create a minimal repro but i will try when i have some time later

Yes, it would be helpful if you could create a reproduction. :) I added my reproduction to https://github.com/biomejs/biome-vscode/issues/229#issuecomment-2366808215.

**Comment by vlinder** [comment] 2024-09-24 09:32
I have this same problem with the quickfix. It appears to me that it is waiting for the typescript check to complete before running. The longer the type checking takes the longer the delay appears to be before it saves the file.
Perhaps there could be a way to move the quickfixing before the type checking, maybe into the formatting step, instead?

**Comment by vlechemin** [comment] 2024-09-24 10:17
I have the same problem, but it seems that `source.organizeImports.biome` doesnt do anything, that's why it fixes the slowness. Does it fix imports for you?

**Comment by vlinder** [comment] 2024-09-24 11:25
I have no problems with `source.organizeImports.biome`. It is the `quickfix` setting that seems to cause the slowness.

The `fixAll` setting does not seem to have the slow save issue.

**Comment by vlechemin** [comment] 2024-09-24 13:53
biome 1.9.2 fixed `source.organizeImports.biome` not doing anything :)

**Comment by ragrag** [comment] 2024-10-05 16:03
is there a guide on how to debug this issue or introspect biome trace logs?

i can reproduce it in a private monorepo but only when opening the full workspace in vscode,
if i have only the vue app folder open in vscode this issue is not happening

**Comment by nhedger** [comment] 2024-11-30 21:56
I think it's fair to say that this issue is not specific to the biome extension, so I will close it. Feel free to circle back if new information comes to light.

**Closed by nhedger** 2024-11-30 21:56 UTC
Labels: Waiting for response, Triage

**Comment by JavaScriptBach** [comment] 2024-12-03 04:48
I take it that the underlying issue is being tracked here: https://github.com/microsoft/vscode/issues/232480

Asking the VSCode team to chime in so we can understand the problem is great, but has the Biome team considered re-implementing the LSP with a different incantation, e.g. `source.fixAll.biome` instead of `quickfix.biome`? Other language servers like vscode-eslint don't seem to have this issue, so this could be an easy way to sidestep the problem.

This issue is blocking my company from migrating to Biome, which is a bummer because we would otherwise love to use it.

**Comment by mizdra** [comment] 2024-12-03 06:53
As you say, I think the problem will be solved if Biome uses `source.fixAll.biome` instead of `quickfix.biome`.

Then, We need to guide users to modify `.vscode/settings.json` as follows.

```diff
 {
   "editor.codeActionsOnSave": {
-    "quickfix.biome": "explicit"
+    "source.fixAll.biome": "explicit"
   }
   // ...
 }
```

Even if typescript-language-features delays `source.fixAll.ts` by 500 ms (see [Q3](https://github.com/microsoft/vscode/issues/232480)), it will not affect users who use `source.fixAll.biome`. I don't think Biome will be affected by whatever decision the VS Code development team makes.

**Comment by JavaScriptBach** [comment] 2024-12-03 07:45
I get the reluctance to ship a new major version as a maintainer. All I can say as an interested potential user is that I'd love to see this problem get solved sooner. (We have a large Typescript mono-repo that we unsuccessfully tried to migrate to Biome earlier this year, and it was blocked only by the VSCode extension performance, as the CLI itself is very fast.)

I did some digging in the docs. The [LSP protocol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeActionKind) doesn't say anything about the distinction between a quickfix and a fixall, except that they are different code actions.

However, the [VSCode Typescript docs](https://code.visualstudio.com/docs/typescript/typescript-refactoring#_code-actions-on-save) suggest that "fixall" is the action intended to be used on save because it will compute all the fixes in one round.

By contrast, a [quickfix](https://code.visualstudio.com/docs/typescript/typescript-refactoring#_quick-fixes) is mentioned as an individual suggestion designed to be handled one at a time, and it seems to be listed as an alternative to a "refactor" code action.

**Comment by JavaScriptBach** [comment] 2024-12-09 18:28
@mizdra would you accept a patch to use `source.fixAll.biome` if it results in better performance? Trying to see if there's anything I can do here to help move things along.

**Comment by mizdra** [comment] 2024-12-09 23:39
@JavaScriptBach I am not sure what you mean by "patch." However, you are free to use all the code I used to report this issue and the vscode team. I disclaim their copyright:)

**Comment by JavaScriptBach** [comment] 2024-12-10 05:34
I just saw there is https://github.com/biomejs/biome/issues/3339. Does this mean that `source.fixAll.biome` was already implemented?

**Comment by OliverJAsh** [comment] 2024-12-10 07:53
`source.fixAll.biome` seems to work on my end. I think [the documentation](https://biomejs.dev/reference/vscode/#fix-on-save) needs updating.
