### ISSUE TITLE
🐛 Autofix on save breaks imports

### ISSUE THREAD

**Issue by OliverJAsh** [biomejs/biome-vscode#179] opened 2024-03-28 08:48 UTC
### VS Code version

1.87.2

### Extension version

2.2.2

### Biome version

1.6.3

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

When `noUnusedImports` is enabled, autofix on save breaks the imports.

### Steps to reproduce

Full reduced test case: https://github.com/OliverJAsh/biome-vscode-quickfix-import-issue. Contents inlined below.

Given:

`biome.json`:
```json
{
    "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
    "linter": {
      "enabled": true,
      "rules": {
        "correctness": {
          "noUnusedImports": "warn"
        }
      }
    }
  }
  
```

`.vscode/settings.json`:
```json
{
    "editor.codeActionsOnSave": {
      "quickfix.biome": "explicit"
    }
  }
  
```

`index.ts`:
```ts
import { A } from 'a';
import { B } from 'b';
import { C } from 'c';

// edit this comment and save the file

```

When I save `index.ts` and the autofix runs, I end up with broken imports:

```ts
import { B } from 'b';
import { 

```

### Expected behavior

Imports are not broken.

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

**Comment by Sec-ant** [comment] 2024-03-28 08:52
This is not a an extension issue and we already have many reports. Close as a duplicate of https://github.com/biomejs/biome/issues/2222. Please track the issue in the main repo.

**Closed** 2024-03-28 08:52 UTC
Labels: Triage
